name: Actions Workflow

on:
  push:
  pull_request:
    types: [closed, reopened, opened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: List Files After Checkout
        run: |
          pwd
          ls -a